version: '3.1'

services:

  redmine:
    image: redmine:3.4.2
    container_name: redmine
    depends_on:
      - redmine-db
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: v338MiHq6CXUAQ3xLr
    restart: unless-stopped
    volumes:
      - /path/to/project/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml:ro
      - /path/to/project/redmine/files:/usr/src/redmine/files
      - /path/to/project/redmine/plugins:/usr/src/redmine/plugins
      - /path/to/project/redmine/log:/usr/src/redmine/log
    networks:
      - redmine-db
      - env_redmine-proxy

  redmine-db:
    image: mysql:5.7
    container_name: remine-db
    volumes:
      - redmine-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: v338MiHq6CXUAQ3xLr
      MYSQL_DATABASE: redmine
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    restart: unless-stopped
    networks:
      - redmine-db

volumes:
  redmine-database:


networks:
  env_redmine-proxy:
    external: true
  redmine-db:
